export type LangCode = 'en' | 'pl' | 'fr' | 'es'
export type CategoryId =
  | 'home'
  | 'food'
  | 'animals'
  | 'city'
  | 'people'
  | 'body'
  | 'clothing'
  | 'nature'
  | 'actions'
  | 'descriptions'
export type ModeId = 'learn' | 'choice' | 'type'

export type Mode = {
  id: ModeId
  label: string
  detail: string
  emoji: string
}

export type LanguageOption = {
  code: LangCode
  label: string
  nativeName: string
  bcp47: string
  voiceLangs: string[]
}

export type Category = {
  id: CategoryId
  label: string
  short: string
  emoji: string
  tint: string
}

export type Word = {
  id: string
  category: CategoryId
  emoji: string
  tint: string
  forms: Record<LangCode, string>
}

export const languages: LanguageOption[] = [
  {
    code: 'en',
    label: 'English',
    nativeName: 'English',
    bcp47: 'en-US',
    voiceLangs: ['en-US', 'en-GB', 'en-AU', 'en-IN', 'en-IE', 'en'],
  },
  {
    code: 'pl',
    label: 'Polish',
    nativeName: 'Polski',
    bcp47: 'pl-PL',
    voiceLangs: ['pl-PL', 'pl'],
  },
  {
    code: 'fr',
    label: 'French',
    nativeName: 'Français',
    bcp47: 'fr-FR',
    voiceLangs: ['fr-FR', 'fr-CA', 'fr-BE', 'fr'],
  },
  {
    code: 'es',
    label: 'Spanish',
    nativeName: 'Español',
    bcp47: 'es-ES',
    voiceLangs: ['es-ES', 'es-MX', 'es-US', 'es-AR', 'es-CO', 'es'],
  },
]

export const categories: Category[] = [
  { id: 'home', label: 'Home', short: 'Home', emoji: '🏠', tint: '#2c241c' },
  { id: 'food', label: 'Food & Drink', short: 'Food', emoji: '🍽️', tint: '#3a2418' },
  { id: 'animals', label: 'Animals', short: 'Animals', emoji: '🐾', tint: '#243018' },
  { id: 'city', label: 'City & Transport', short: 'City', emoji: '🏙️', tint: '#1a2430' },
  { id: 'people', label: 'People & Family', short: 'People', emoji: '👪', tint: '#3a2820' },
  { id: 'body', label: 'Body & Health', short: 'Body', emoji: '💪', tint: '#301820' },
  { id: 'clothing', label: 'Clothing & Personal Items', short: 'Clothes', emoji: '👕', tint: '#2c2030' },
  { id: 'nature', label: 'Nature & Weather', short: 'Nature', emoji: '🌿', tint: '#1c2c18' },
  { id: 'actions', label: 'Everyday Actions', short: 'Actions', emoji: '🏃', tint: '#242018' },
  { id: 'descriptions', label: 'Descriptions & Emotions', short: 'Feelings', emoji: '😊', tint: '#302028' },
]

export const modes: Mode[] = [
  { id: 'learn', label: 'Learn', detail: 'Scroll, see, and hear each word', emoji: '📖' },
  { id: 'choice', label: 'Multiple choice', detail: 'Pick the right word from three', emoji: '✅' },
  { id: 'type', label: 'Typing', detail: 'Type the word yourself', emoji: '⌨️' },
]

function tintFor(category: CategoryId): string {
  return categories.find((item) => item.id === category)?.tint ?? '#16120e'
}

function word(
  id: string,
  category: CategoryId,
  emoji: string,
  en: string,
  pl: string,
  fr: string,
  es: string,
): Word {
  return { id, category, emoji, tint: tintFor(category), forms: { en, pl, fr, es } }
}

export const words: Word[] = [
  word('spoon', 'home', '🥄', 'spoon', 'łyżka', 'cuillère', 'cuchara'),
  word('fork', 'home', '🍴', 'fork', 'widelec', 'fourchette', 'tenedor'),
  word('knife', 'home', '🔪', 'knife', 'nóż', 'couteau', 'cuchillo'),
  word('plate', 'home', '🍽️', 'plate', 'talerz', 'assiette', 'plato'),
  word('cup', 'home', '☕', 'cup', 'kubek', 'tasse', 'taza'),
  word('chair', 'home', '🪑', 'chair', 'krzesło', 'chaise', 'silla'),
  word('sofa', 'home', '🛋️', 'sofa', 'kanapa', 'canapé', 'sofá'),
  word('bed', 'home', '🛏️', 'bed', 'łóżko', 'lit', 'cama'),
  word('door', 'home', '🚪', 'door', 'drzwi', 'porte', 'puerta'),
  word('window', 'home', '🪟', 'window', 'okno', 'fenêtre', 'ventana'),
  word('key', 'home', '🔑', 'key', 'klucz', 'clé', 'llave'),
  word('lamp', 'home', '💡', 'lamp', 'lampa', 'lampe', 'lámpara'),
  word('clock', 'home', '⏰', 'clock', 'zegar', 'horloge', 'reloj'),
  word('soap', 'home', '🧼', 'soap', 'mydło', 'savon', 'jabón'),
  word('book', 'home', '📖', 'book', 'książka', 'livre', 'libro'),
  word('phone', 'home', '📱', 'phone', 'telefon', 'téléphone', 'teléfono'),
  word('shower', 'home', '🚿', 'shower', 'prysznic', 'douche', 'ducha'),
  word('toilet', 'home', '🚽', 'toilet', 'toaleta', 'toilettes', 'váter'),
  word('television', 'home', '📺', 'television', 'telewizor', 'télévision', 'televisión'),
  word('broom', 'home', '🧹', 'broom', 'miotła', 'balai', 'escoba'),
  word('table', 'home', '🪵', 'table', 'stół', 'table', 'mesa'),
  word('fridge', 'home', '🧊', 'fridge', 'lodówka', 'réfrigérateur', 'nevera'),
  word('oven', 'home', '♨️', 'oven', 'piekarnik', 'four', 'horno'),
  word('sink', 'home', '🚰', 'sink', 'zlew', 'évier', 'fregadero'),
  word('pillow', 'home', '🛌', 'pillow', 'poduszka', 'oreiller', 'almohada'),
  word('blanket', 'home', '🧶', 'blanket', 'koc', 'couverture', 'manta'),
  word('towel', 'home', '🧖', 'towel', 'ręcznik', 'serviette', 'toalla'),
  word('mirror', 'home', '🪞', 'mirror', 'lustro', 'miroir', 'espejo'),
  word('microwave', 'home', '📡', 'microwave', 'mikrofalówka', 'micro-ondes', 'microondas'),
  word('carpet', 'home', '🟫', 'carpet', 'dywan', 'tapis', 'alfombra'),
  word('curtain', 'home', '🧵', 'curtain', 'zasłona', 'rideau', 'cortina'),
  word('shelf', 'home', '📚', 'shelf', 'półka', 'étagère', 'estante'),
  word('trash', 'home', '🗑️', 'trash can', 'kosz', 'poubelle', 'basura'),
  word('candle', 'home', '🕯️', 'candle', 'świeca', 'bougie', 'vela'),
  word('houseplant', 'home', '🪴', 'plant', 'roślina', 'plante', 'planta'),
  word('washer', 'home', '🧺', 'washing machine', 'pralka', 'lave-linge', 'lavadora'),
  word('computer', 'home', '💻', 'computer', 'komputer', 'ordinateur', 'computadora'),
  word('charger', 'home', '🔌', 'charger', 'ładowarka', 'chargeur', 'cargador'),
  word('stairs', 'home', '🪜', 'stairs', 'schody', 'escalier', 'escaleras'),
  word('mailbox', 'home', '📫', 'mailbox', 'skrzynka', 'boîte aux lettres', 'buzón'),
  word('bowl', 'home', '🥣', 'bowl', 'miska', 'bol', 'bol'),
  word('pan', 'home', '🍳', 'pan', 'patelnia', 'poêle', 'sartén'),
  word('glass', 'home', '🥃', 'glass', 'szklanka', 'verre', 'vaso'),
  word('napkin', 'home', '🧻', 'napkin', 'serwetka', 'serviette de table', 'servilleta'),
  word('drawer', 'home', '🗃️', 'drawer', 'szuflada', 'tiroir', 'cajón'),

  word('water', 'food', '💧', 'water', 'woda', 'eau', 'agua'),
  word('bread', 'food', '🍞', 'bread', 'chleb', 'pain', 'pan'),
  word('apple', 'food', '🍎', 'apple', 'jabłko', 'pomme', 'manzana'),
  word('banana', 'food', '🍌', 'banana', 'banan', 'banane', 'plátano'),
  word('orange', 'food', '🍊', 'orange', 'pomarańcza', 'orange', 'naranja'),
  word('cheese', 'food', '🧀', 'cheese', 'ser', 'fromage', 'queso'),
  word('milk', 'food', '🥛', 'milk', 'mleko', 'lait', 'leche'),
  word('coffee', 'food', '☕', 'coffee', 'kawa', 'café', 'café'),
  word('tea', 'food', '🍵', 'tea', 'herbata', 'thé', 'té'),
  word('wine', 'food', '🍷', 'wine', 'wino', 'vin', 'vino'),
  word('beer', 'food', '🍺', 'beer', 'piwo', 'bière', 'cerveza'),
  word('egg', 'food', '🥚', 'egg', 'jajko', 'œuf', 'huevo'),
  word('meat', 'food', '🥩', 'meat', 'mięso', 'viande', 'carne'),
  word('rice', 'food', '🍚', 'rice', 'ryż', 'riz', 'arroz'),
  word('pasta', 'food', '🍝', 'pasta', 'makaron', 'pâtes', 'pasta'),
  word('soup', 'food', '🍲', 'soup', 'zupa', 'soupe', 'sopa'),
  word('cake', 'food', '🍰', 'cake', 'ciasto', 'gâteau', 'pastel'),
  word('ice-cream', 'food', '🍦', 'ice cream', 'lody', 'glace', 'helado'),
  word('salt', 'food', '🧂', 'salt', 'sól', 'sel', 'sal'),
  word('honey', 'food', '🍯', 'honey', 'miód', 'miel', 'miel'),
  word('tomato', 'food', '🍅', 'tomato', 'pomidor', 'tomate', 'tomate'),
  word('potato', 'food', '🥔', 'potato', 'ziemniak', 'pomme de terre', 'patata'),
  word('carrot', 'food', '🥕', 'carrot', 'marchewka', 'carotte', 'zanahoria'),
  word('salad', 'food', '🥗', 'salad', 'sałatka', 'salade', 'ensalada'),
  word('pizza', 'food', '🍕', 'pizza', 'pizza', 'pizza', 'pizza'),
  word('burger', 'food', '🍔', 'burger', 'hamburger', 'hamburger', 'hamburguesa'),
  word('sandwich', 'food', '🥪', 'sandwich', 'kanapka', 'sandwich', 'sándwich'),
  word('chicken-food', 'food', '🍗', 'chicken', 'kurczak', 'poulet', 'pollo'),
  word('juice', 'food', '🧃', 'juice', 'sok', 'jus', 'jugo'),
  word('sugar', 'food', '🍬', 'sugar', 'cukier', 'sucre', 'azúcar'),
  word('pepper', 'food', '🌶️', 'pepper', 'pieprz', 'poivre', 'pimienta'),
  word('oil', 'food', '🫒', 'oil', 'olej', 'huile', 'aceite'),
  word('butter', 'food', '🧈', 'butter', 'masło', 'beurre', 'mantequilla'),
  word('yogurt', 'food', '🫙', 'yogurt', 'jogurt', 'yaourt', 'yogur'),
  word('strawberry', 'food', '🍓', 'strawberry', 'truskawka', 'fraise', 'fresa'),
  word('grape', 'food', '🍇', 'grape', 'winogrono', 'raisin', 'uva'),
  word('lemon', 'food', '🍋', 'lemon', 'cytryna', 'citron', 'limón'),
  word('chocolate', 'food', '🍫', 'chocolate', 'czekolada', 'chocolat', 'chocolate'),
  word('cookie', 'food', '🍪', 'cookie', 'ciastko', 'biscuit', 'galleta'),
  word('croissant', 'food', '🥐', 'croissant', 'rogalik', 'croissant', 'cruasán'),
  word('mushroom', 'food', '🍄', 'mushroom', 'grzyb', 'champignon', 'champiñón'),
  word('peach', 'food', '🍑', 'peach', 'brzoskwinia', 'pêche', 'melocotón'),
  word('corn', 'food', '🌽', 'corn', 'kukurydza', 'maïs', 'maíz'),
  word('donut', 'food', '🍩', 'donut', 'pączek', 'doughnut', 'donut'),
  word('popcorn', 'food', '🍿', 'popcorn', 'popcorn', 'pop-corn', 'palomitas'),

  word('cat', 'animals', '🐱', 'cat', 'kot', 'chat', 'gato'),
  word('dog', 'animals', '🐶', 'dog', 'pies', 'chien', 'perro'),
  word('bird', 'animals', '🐦', 'bird', 'ptak', 'oiseau', 'pájaro'),
  word('fish', 'animals', '🐟', 'fish', 'ryba', 'poisson', 'pez'),
  word('horse', 'animals', '🐴', 'horse', 'koń', 'cheval', 'caballo'),
  word('cow', 'animals', '🐮', 'cow', 'krowa', 'vache', 'vaca'),
  word('pig', 'animals', '🐷', 'pig', 'świnia', 'cochon', 'cerdo'),
  word('sheep', 'animals', '🐑', 'sheep', 'owca', 'mouton', 'oveja'),
  word('chicken', 'animals', '🐔', 'chicken', 'kura', 'poule', 'gallina'),
  word('rabbit', 'animals', '🐰', 'rabbit', 'królik', 'lapin', 'conejo'),
  word('mouse', 'animals', '🐭', 'mouse', 'mysz', 'souris', 'ratón'),
  word('frog', 'animals', '🐸', 'frog', 'żaba', 'grenouille', 'rana'),
  word('bee', 'animals', '🐝', 'bee', 'pszczoła', 'abeille', 'abeja'),
  word('butterfly', 'animals', '🦋', 'butterfly', 'motyl', 'papillon', 'mariposa'),
  word('bear', 'animals', '🐻', 'bear', 'niedźwiedź', 'ours', 'oso'),
  word('lion', 'animals', '🦁', 'lion', 'lew', 'lion', 'león'),
  word('duck', 'animals', '🦆', 'duck', 'kaczka', 'canard', 'pato'),
  word('elephant', 'animals', '🐘', 'elephant', 'słoń', 'éléphant', 'elefante'),
  word('snake', 'animals', '🐍', 'snake', 'wąż', 'serpent', 'serpiente'),
  word('turtle', 'animals', '🐢', 'turtle', 'żółw', 'tortue', 'tortuga'),
  word('wolf', 'animals', '🐺', 'wolf', 'wilk', 'loup', 'lobo'),
  word('fox', 'animals', '🦊', 'fox', 'lis', 'renard', 'zorro'),
  word('deer', 'animals', '🦌', 'deer', 'jeleń', 'cerf', 'ciervo'),
  word('tiger', 'animals', '🐯', 'tiger', 'tygrys', 'tigre', 'tigre'),
  word('monkey', 'animals', '🐵', 'monkey', 'małpa', 'singe', 'mono'),
  word('penguin', 'animals', '🐧', 'penguin', 'pingwin', 'pingouin', 'pingüino'),
  word('whale', 'animals', '🐋', 'whale', 'wieloryb', 'baleine', 'ballena'),
  word('dolphin', 'animals', '🐬', 'dolphin', 'delfin', 'dauphin', 'delfín'),
  word('shark', 'animals', '🦈', 'shark', 'rekin', 'requin', 'tiburón'),
  word('goat', 'animals', '🐐', 'goat', 'koza', 'chèvre', 'cabra'),
  word('donkey', 'animals', '🫏', 'donkey', 'osioł', 'âne', 'burro'),
  word('owl', 'animals', '🦉', 'owl', 'sowa', 'hibou', 'búho'),
  word('spider', 'animals', '🕷️', 'spider', 'pająk', 'araignée', 'araña'),
  word('ant', 'animals', '🐜', 'ant', 'mrówka', 'fourmi', 'hormiga'),
  word('crab', 'animals', '🦀', 'crab', 'krab', 'crabe', 'cangrejo'),
  word('octopus', 'animals', '🐙', 'octopus', 'ośmiornica', 'pieuvre', 'pulpo'),
  word('panda', 'animals', '🐼', 'panda', 'panda', 'panda', 'panda'),
  word('zebra', 'animals', '🦓', 'zebra', 'zebra', 'zèbre', 'cebra'),
  word('giraffe', 'animals', '🦒', 'giraffe', 'żyrafa', 'girafe', 'jirafa'),
  word('kangaroo', 'animals', '🦘', 'kangaroo', 'kangur', 'kangourou', 'canguro'),
  word('squirrel', 'animals', '🐿️', 'squirrel', 'wiewiórka', 'écureuil', 'ardilla'),
  word('swan', 'animals', '🦢', 'swan', 'łabędź', 'cygne', 'cisne'),
  word('crocodile', 'animals', '🐊', 'crocodile', 'krokodyl', 'crocodile', 'cocodrilo'),
  word('camel', 'animals', '🐪', 'camel', 'wielbłąd', 'chameau', 'camello'),
  word('seal', 'animals', '🦭', 'seal', 'foka', 'phoque', 'foca'),

  word('car', 'city', '🚗', 'car', 'samochód', 'voiture', 'coche'),
  word('bus', 'city', '🚌', 'bus', 'autobus', 'bus', 'autobús'),
  word('train', 'city', '🚆', 'train', 'pociąg', 'train', 'tren'),
  word('bicycle', 'city', '🚲', 'bicycle', 'rower', 'vélo', 'bicicleta'),
  word('taxi', 'city', '🚕', 'taxi', 'taksówka', 'taxi', 'taxi'),
  word('airplane', 'city', '✈️', 'airplane', 'samolot', 'avion', 'avión'),
  word('boat', 'city', '⛵', 'boat', 'łódź', 'bateau', 'barco'),
  word('metro', 'city', '🚇', 'metro', 'metro', 'métro', 'metro'),
  word('motorcycle', 'city', '🏍️', 'motorcycle', 'motocykl', 'moto', 'motocicleta'),
  word('traffic-light', 'city', '🚦', 'traffic light', 'światła', 'feu', 'semáforo'),
  word('road', 'city', '🛣️', 'road', 'droga', 'route', 'carretera'),
  word('bridge', 'city', '🌉', 'bridge', 'most', 'pont', 'puente'),
  word('map', 'city', '🗺️', 'map', 'mapa', 'carte', 'mapa'),
  word('station', 'city', '🚉', 'station', 'dworzec', 'gare', 'estación'),
  word('ticket', 'city', '🎫', 'ticket', 'bilet', 'billet', 'billete'),
  word('suitcase', 'city', '🧳', 'suitcase', 'walizka', 'valise', 'maleta'),
  word('hotel', 'city', '🏨', 'hotel', 'hotel', 'hôtel', 'hotel'),
  word('shop', 'city', '🏪', 'shop', 'sklep', 'magasin', 'tienda'),
  word('school', 'city', '🏫', 'school', 'szkoła', 'école', 'escuela'),
  word('hospital', 'city', '🏥', 'hospital', 'szpital', 'hôpital', 'hospital'),
  word('library', 'city', '📚', 'library', 'biblioteka', 'bibliothèque', 'biblioteca'),
  word('bank', 'city', '🏦', 'bank', 'bank', 'banque', 'banco'),
  word('church', 'city', '⛪', 'church', 'kościół', 'église', 'iglesia'),
  word('airport', 'city', '🛫', 'airport', 'lotnisko', 'aéroport', 'aeropuerto'),
  word('park', 'city', '🛝', 'park', 'park', 'parc', 'parque'),
  word('street', 'city', '🏘️', 'street', 'ulica', 'rue', 'calle'),
  word('parking', 'city', '🅿️', 'parking', 'parking', 'parking', 'aparcamiento'),
  word('tram', 'city', '🚊', 'tram', 'tramwaj', 'tram', 'tranvía'),
  word('truck', 'city', '🚚', 'truck', 'ciężarówka', 'camion', 'camión'),
  word('stop', 'city', '🛑', 'stop', 'stop', 'stop', 'stop'),
  word('museum', 'city', '🏛️', 'museum', 'muzeum', 'musée', 'museo'),
  word('cafe', 'city', '🧋', 'cafe', 'kawiarnia', 'café', 'café'),
  word('post-office', 'city', '📮', 'post office', 'poczta', 'poste', 'correos'),
  word('market', 'city', '🛒', 'market', 'targ', 'marché', 'mercado'),
  word('fountain', 'city', '⛲', 'fountain', 'fontanna', 'fontaine', 'fuente'),
  word('office', 'city', '🏢', 'office', 'biuro', 'bureau', 'oficina'),
  word('gas-station', 'city', '⛽', 'gas station', 'stacja', 'station-service', 'gasolinera'),
  word('elevator', 'city', '🛗', 'elevator', 'winda', 'ascenseur', 'ascensor'),
  word('harbor', 'city', '⚓', 'harbor', 'port', 'port', 'puerto'),
  word('factory', 'city', '🏭', 'factory', 'fabryka', 'usine', 'fábrica'),
  word('restaurant', 'city', '🍜', 'restaurant', 'restauracja', 'restaurant', 'restaurante'),
  word('crosswalk', 'city', '🚸', 'crosswalk', 'przejście', 'passage piéton', 'paso de peatones'),
  word('pharmacy', 'city', '⚕️', 'pharmacy', 'apteka', 'pharmacie', 'farmacia'),
  word('plaza', 'city', '🟦', 'square', 'plac', 'place', 'plaza'),
  word('stadium', 'city', '🏟️', 'stadium', 'stadion', 'stade', 'estadio'),

  word('man', 'people', '👨', 'man', 'mężczyzna', 'homme', 'hombre'),
  word('woman', 'people', '👩', 'woman', 'kobieta', 'femme', 'mujer'),
  word('boy', 'people', '👦', 'boy', 'chłopiec', 'garçon', 'chico'),
  word('girl', 'people', '👧', 'girl', 'dziewczynka', 'fille', 'niña'),
  word('baby', 'people', '👶', 'baby', 'niemowlę', 'bébé', 'bebé'),
  word('child', 'people', '🧒', 'child', 'dziecko', 'enfant', 'niño'),
  word('mother', 'people', '👩', 'mother', 'matka', 'mère', 'madre'),
  word('father', 'people', '👨', 'father', 'ojciec', 'père', 'padre'),
  word('brother', 'people', '👦', 'brother', 'brat', 'frère', 'hermano'),
  word('sister', 'people', '👧', 'sister', 'siostra', 'sœur', 'hermana'),
  word('grandmother', 'people', '👵', 'grandmother', 'babcia', 'grand-mère', 'abuela'),
  word('grandfather', 'people', '👴', 'grandfather', 'dziadek', 'grand-père', 'abuelo'),
  word('family', 'people', '👪', 'family', 'rodzina', 'famille', 'familia'),
  word('friend', 'people', '🤝', 'friend', 'przyjaciel', 'ami', 'amigo'),
  word('teacher', 'people', '👩‍🏫', 'teacher', 'nauczyciel', 'enseignant', 'maestro'),
  word('doctor', 'people', '👨‍⚕️', 'doctor', 'lekarz', 'médecin', 'médico'),
  word('student', 'people', '🎓', 'student', 'uczeń', 'élève', 'estudiante'),
  word('cook', 'people', '🧑‍🍳', 'cook', 'kucharz', 'cuisinier', 'cocinero'),
  word('police', 'people', '👮', 'police officer', 'policjant', 'policier', 'policía'),
  word('nurse', 'people', '🩺', 'nurse', 'pielęgniarka', 'infirmière', 'enfermera'),
  word('aunt', 'people', '👩', 'aunt', 'ciocia', 'tante', 'tía'),
  word('uncle', 'people', '👨', 'uncle', 'wujek', 'oncle', 'tío'),
  word('cousin', 'people', '🧒', 'cousin', 'kuzyn', 'cousin', 'primo'),
  word('husband', 'people', '🤵', 'husband', 'mąż', 'mari', 'esposo'),
  word('wife', 'people', '👰', 'wife', 'żona', 'épouse', 'esposa'),
  word('son', 'people', '👦', 'son', 'syn', 'fils', 'hijo'),
  word('daughter', 'people', '👧', 'daughter', 'córka', 'fille', 'hija'),
  word('neighbor', 'people', '🏡', 'neighbor', 'sąsiad', 'voisin', 'vecino'),
  word('boss', 'people', '👔', 'boss', 'szef', 'patron', 'jefe'),
  word('waiter', 'people', '🧑‍🍽️', 'waiter', 'kelner', 'serveur', 'camarero'),
  word('farmer', 'people', '🚜', 'farmer', 'rolnik', 'agriculteur', 'granjero'),
  word('driver', 'people', '🚗', 'driver', 'kierowca', 'chauffeur', 'conductor'),
  word('singer', 'people', '🎤', 'singer', 'piosenkarz', 'chanteur', 'cantante'),
  word('artist', 'people', '🎨', 'artist', 'artysta', 'artiste', 'artista'),
  word('athlete', 'people', '🏅', 'athlete', 'sportowiec', 'athlète', 'atleta'),
  word('firefighter', 'people', '🚒', 'firefighter', 'strażak', 'pompier', 'bombero'),
  word('engineer', 'people', '🛠️', 'engineer', 'inżynier', 'ingénieur', 'ingeniero'),
  word('soldier', 'people', '🪖', 'soldier', 'żołnierz', 'soldat', 'soldado'),
  word('tourist', 'people', '📷', 'tourist', 'turysta', 'touriste', 'turista'),
  word('guest', 'people', '🛎️', 'guest', 'gość', 'invité', 'invitado'),
  word('lawyer', 'people', '⚖️', 'lawyer', 'prawnik', 'avocat', 'abogado'),
  word('mechanic', 'people', '🔧', 'mechanic', 'mechanik', 'mécanicien', 'mecánico'),
  word('dentist', 'people', '😁', 'dentist', 'dentysta', 'dentiste', 'dentista'),
  word('photographer', 'people', '📸', 'photographer', 'fotograf', 'photographe', 'fotógrafo'),
  word('journalist', 'people', '📰', 'journalist', 'dziennikarz', 'journaliste', 'periodista'),

  word('head', 'body', '🗣️', 'head', 'głowa', 'tête', 'cabeza'),
  word('eye', 'body', '👁️', 'eye', 'oko', 'œil', 'ojo'),
  word('ear', 'body', '👂', 'ear', 'ucho', 'oreille', 'oreja'),
  word('nose', 'body', '👃', 'nose', 'nos', 'nez', 'nariz'),
  word('mouth', 'body', '👄', 'mouth', 'usta', 'bouche', 'boca'),
  word('tooth', 'body', '🦷', 'tooth', 'ząb', 'dent', 'diente'),
  word('hand', 'body', '✋', 'hand', 'ręka', 'main', 'mano'),
  word('foot', 'body', '🦶', 'foot', 'stopa', 'pied', 'pie'),
  word('arm', 'body', '💪', 'arm', 'ramię', 'bras', 'brazo'),
  word('leg', 'body', '🦵', 'leg', 'noga', 'jambe', 'pierna'),
  word('heart', 'body', '❤️', 'heart', 'serce', 'cœur', 'corazón'),
  word('brain', 'body', '🧠', 'brain', 'mózg', 'cerveau', 'cerebro'),
  word('bone', 'body', '🦴', 'bone', 'kość', 'os', 'hueso'),
  word('blood', 'body', '🩸', 'blood', 'krew', 'sang', 'sangre'),
  word('medicine', 'body', '💊', 'medicine', 'lek', 'médicament', 'medicamento'),
  word('bandage', 'body', '🩹', 'bandage', 'plaster', 'pansement', 'tirita'),
  word('thermometer', 'body', '🌡️', 'thermometer', 'termometr', 'thermomètre', 'termómetro'),
  word('ambulance', 'body', '🚑', 'ambulance', 'karetka', 'ambulance', 'ambulancia'),
  word('mask', 'body', '😷', 'mask', 'maseczka', 'masque', 'mascarilla'),
  word('vaccine', 'body', '💉', 'vaccine', 'szczepionka', 'vaccin', 'vacuna'),
  word('hair', 'body', '💇', 'hair', 'włosy', 'cheveux', 'pelo'),
  word('face', 'body', '🙂', 'face', 'twarz', 'visage', 'cara'),
  word('neck', 'body', '🧣', 'neck', 'szyja', 'cou', 'cuello'),
  word('shoulder', 'body', '🤷', 'shoulder', 'bark', 'épaule', 'hombro'),
  word('finger', 'body', '☝️', 'finger', 'palec', 'doigt', 'dedo'),
  word('knee', 'body', '🦵', 'knee', 'kolano', 'genou', 'rodilla'),
  word('back', 'body', '🔙', 'back', 'plecy', 'dos', 'espalda'),
  word('stomach', 'body', '🤢', 'stomach', 'brzuch', 'ventre', 'estómago'),
  word('skin', 'body', '🧴', 'skin', 'skóra', 'peau', 'piel'),
  word('fever', 'body', '🤒', 'fever', 'gorączka', 'fièvre', 'fiebre'),
  word('cough', 'body', '🤧', 'cough', 'kaszel', 'toux', 'tos'),
  word('pain', 'body', '😣', 'pain', 'ból', 'douleur', 'dolor'),
  word('tongue', 'body', '👅', 'tongue', 'język', 'langue', 'lengua'),
  word('lungs', 'body', '🫁', 'lungs', 'płuca', 'poumons', 'pulmones'),
  word('health', 'body', '💚', 'health', 'zdrowie', 'santé', 'salud'),
  word('muscle', 'body', '💪', 'muscle', 'mięsień', 'muscle', 'músculo'),
  word('throat', 'body', '🗣️', 'throat', 'gardło', 'gorge', 'garganta'),
  word('wrist', 'body', '⌚', 'wrist', 'nadgarstek', 'poignet', 'muñeca'),
  word('sick', 'body', '🤮', 'sick', 'chory', 'malade', 'enfermo'),
  word('injury', 'body', '🤕', 'injury', 'rana', 'blessure', 'herida'),
  word('vitamin', 'body', '🍊', 'vitamin', 'witamina', 'vitamine', 'vitamina'),
  word('appointment', 'body', '📅', 'appointment', 'wizyta', 'rendez-vous', 'cita'),
  word('rest', 'body', '😌', 'rest', 'odpoczynek', 'repos', 'descanso'),
  word('smile', 'body', '😁', 'smile', 'uśmiech', 'sourire', 'sonrisa'),
  word('ankle', 'body', '🦶', 'ankle', 'kostka', 'cheville', 'tobillo'),

  word('shirt', 'clothing', '👕', 'shirt', 'koszula', 'chemise', 'camisa'),
  word('pants', 'clothing', '👖', 'pants', 'spodnie', 'pantalon', 'pantalones'),
  word('dress', 'clothing', '👗', 'dress', 'sukienka', 'robe', 'vestido'),
  word('coat', 'clothing', '🧥', 'coat', 'płaszcz', 'manteau', 'abrigo'),
  word('socks', 'clothing', '🧦', 'socks', 'skarpety', 'chaussettes', 'calcetines'),
  word('shoes', 'clothing', '👟', 'shoes', 'buty', 'chaussures', 'zapatos'),
  word('boots', 'clothing', '🥾', 'boots', 'kozaki', 'bottes', 'botas'),
  word('hat', 'clothing', '🧢', 'hat', 'czapka', 'casquette', 'gorra'),
  word('glasses', 'clothing', '👓', 'glasses', 'okulary', 'lunettes', 'gafas'),
  word('watch', 'clothing', '⌚', 'watch', 'zegarek', 'montre', 'reloj'),
  word('bag', 'clothing', '👜', 'bag', 'torba', 'sac', 'bolsa'),
  word('backpack', 'clothing', '🎒', 'backpack', 'plecak', 'sac à dos', 'mochila'),
  word('umbrella', 'clothing', '☂️', 'umbrella', 'parasol', 'parapluie', 'paraguas'),
  word('ring', 'clothing', '💍', 'ring', 'pierścionek', 'bague', 'anillo'),
  word('necklace', 'clothing', '📿', 'necklace', 'naszyjnik', 'collier', 'collar'),
  word('comb', 'clothing', '🪮', 'comb', 'grzebień', 'peigne', 'peine'),
  word('lipstick', 'clothing', '💄', 'lipstick', 'szminka', 'rouge à lèvres', 'pintalabios'),
  word('toothbrush', 'clothing', '🪥', 'toothbrush', 'szczoteczka', 'brosse à dents', 'cepillo'),
  word('scarf', 'clothing', '🧣', 'scarf', 'szalik', 'écharpe', 'bufanda'),
  word('gloves', 'clothing', '🧤', 'gloves', 'rękawiczki', 'gants', 'guantes'),
  word('jacket', 'clothing', '🧥', 'jacket', 'kurtka', 'veste', 'chaqueta'),
  word('sweater', 'clothing', '🧶', 'sweater', 'sweter', 'pull', 'suéter'),
  word('skirt', 'clothing', '👗', 'skirt', 'spódnica', 'jupe', 'falda'),
  word('shorts', 'clothing', '🩳', 'shorts', 'szorty', 'short', 'pantalones cortos'),
  word('pajamas', 'clothing', '👘', 'pajamas', 'piżama', 'pyjama', 'pijama'),
  word('belt', 'clothing', '🎗️', 'belt', 'pasek', 'ceinture', 'cinturón'),
  word('tie', 'clothing', '👔', 'tie', 'krawat', 'cravate', 'corbata'),
  word('earrings', 'clothing', '💎', 'earrings', 'kolczyki', 'boucles d’oreilles', 'pendientes'),
  word('wallet', 'clothing', '👛', 'wallet', 'portfel', 'portefeuille', 'cartera'),
  word('perfume', 'clothing', '💐', 'perfume', 'perfumy', 'parfum', 'perfume'),
  word('slippers', 'clothing', '🥿', 'slippers', 'kapcie', 'pantoufles', 'zapatillas'),
  word('sandals', 'clothing', '👡', 'sandals', 'sandały', 'sandales', 'sandalias'),
  word('hoodie', 'clothing', '👕', 'hoodie', 'bluza', 'sweat', 'sudadera'),
  word('makeup', 'clothing', '💅', 'makeup', 'makijaż', 'maquillage', 'maquillaje'),
  word('button', 'clothing', '🔘', 'button', 'guzik', 'bouton', 'botón'),
  word('bikini', 'clothing', '👙', 'swimsuit', 'kostium', 'maillot', 'bañador'),
  word('bracelet', 'clothing', '📿', 'bracelet', 'bransoletka', 'bracelet', 'pulsera'),
  word('helmet', 'clothing', '⛑️', 'helmet', 'kask', 'casque', 'casco'),
  word('jeans', 'clothing', '👖', 'jeans', 'dżinsy', 'jean', 'vaqueros'),
  word('raincoat', 'clothing', '☔', 'raincoat', 'płaszcz przeciwdeszczowy', 'imperméable', 'chubasquero'),
  word('sunglasses', 'clothing', '🕶️', 'sunglasses', 'okulary przeciwsłoneczne', 'lunettes de soleil', 'gafas de sol'),
  word('hairbrush', 'clothing', '🪮', 'hairbrush', 'szczotka', 'brosse', 'cepillo'),
  word('pocket', 'clothing', '👖', 'pocket', 'kieszeń', 'poche', 'bolsillo'),
  word('uniform', 'clothing', '💂', 'uniform', 'mundur', 'uniforme', 'uniforme'),
  word('diaper', 'clothing', '🧷', 'diaper', 'pieluszka', 'couche', 'pañal'),

  word('sun', 'nature', '☀️', 'sun', 'słońce', 'soleil', 'sol'),
  word('moon', 'nature', '🌙', 'moon', 'księżyc', 'lune', 'luna'),
  word('star', 'nature', '⭐', 'star', 'gwiazda', 'étoile', 'estrella'),
  word('cloud', 'nature', '☁️', 'cloud', 'chmura', 'nuage', 'nube'),
  word('rain', 'nature', '🌧️', 'rain', 'deszcz', 'pluie', 'lluvia'),
  word('snow', 'nature', '❄️', 'snow', 'śnieg', 'neige', 'nieve'),
  word('wind', 'nature', '💨', 'wind', 'wiatr', 'vent', 'viento'),
  word('storm', 'nature', '⛈️', 'storm', 'burza', 'orage', 'tormenta'),
  word('tree', 'nature', '🌳', 'tree', 'drzewo', 'arbre', 'árbol'),
  word('flower', 'nature', '🌸', 'flower', 'kwiat', 'fleur', 'flor'),
  word('grass', 'nature', '🌿', 'grass', 'trawa', 'herbe', 'hierba'),
  word('mountain', 'nature', '⛰️', 'mountain', 'góra', 'montagne', 'montaña'),
  word('river', 'nature', '🏞️', 'river', 'rzeka', 'rivière', 'río'),
  word('sea', 'nature', '🌊', 'sea', 'morze', 'mer', 'mar'),
  word('fire', 'nature', '🔥', 'fire', 'ogień', 'feu', 'fuego'),
  word('earth', 'nature', '🌍', 'earth', 'ziemia', 'terre', 'tierra'),
  word('leaf', 'nature', '🍃', 'leaf', 'liść', 'feuille', 'hoja'),
  word('forest', 'nature', '🌲', 'forest', 'las', 'forêt', 'bosque'),
  word('rainbow', 'nature', '🌈', 'rainbow', 'tęcza', 'arc-en-ciel', 'arcoíris'),
  word('weather', 'nature', '⛅', 'weather', 'pogoda', 'temps', 'tiempo'),
  word('sky', 'nature', '🌌', 'sky', 'niebo', 'ciel', 'cielo'),
  word('lake', 'nature', '🛶', 'lake', 'jezioro', 'lac', 'lago'),
  word('beach', 'nature', '🏖️', 'beach', 'plaża', 'plage', 'playa'),
  word('sand', 'nature', '⏳', 'sand', 'piasek', 'sable', 'arena'),
  word('rock', 'nature', '🪨', 'rock', 'kamień', 'rocher', 'piedra'),
  word('island', 'nature', '🏝️', 'island', 'wyspa', 'île', 'isla'),
  word('desert', 'nature', '🏜️', 'desert', 'pustynia', 'désert', 'desierto'),
  word('volcano', 'nature', '🌋', 'volcano', 'wulkan', 'volcan', 'volcán'),
  word('lightning', 'nature', '⚡', 'lightning', 'błyskawica', 'éclair', 'relámpago'),
  word('fog', 'nature', '🌫️', 'fog', 'mgła', 'brouillard', 'niebla'),
  word('ice', 'nature', '🧊', 'ice', 'lód', 'glace', 'hielo'),
  word('spring', 'nature', '🌱', 'spring', 'wiosna', 'printemps', 'primavera'),
  word('autumn', 'nature', '🍂', 'autumn', 'jesień', 'automne', 'otoño'),
  word('summer', 'nature', '🌞', 'summer', 'lato', 'été', 'verano'),
  word('winter', 'nature', '⛄', 'winter', 'zima', 'hiver', 'inverno'),
  word('garden', 'nature', '🏡', 'garden', 'ogród', 'jardin', 'jardín'),
  word('cave', 'nature', '🕳️', 'cave', 'jaskinia', 'grotte', 'cueva'),
  word('sunrise', 'nature', '🌅', 'sunrise', 'wschód słońca', 'lever du soleil', 'amanecer'),
  word('sunset', 'nature', '🌇', 'sunset', 'zachód słońca', 'coucher du soleil', 'atardecer'),
  word('thunder', 'nature', '🌩️', 'thunder', 'grzmot', 'tonnerre', 'trueno'),
  word('wave', 'nature', '🌊', 'wave', 'fala', 'vague', 'ola'),
  word('pond', 'nature', '🐸', 'pond', 'staw', 'étang', 'estanque'),
  word('valley', 'nature', '🏕️', 'valley', 'dolina', 'vallée', 'valle'),
  word('hill', 'nature', '🏔️', 'hill', 'wzgórze', 'colline', 'colina'),
  word('field', 'nature', '🌾', 'field', 'pole', 'champ', 'campo'),

  word('eat', 'actions', '🍽️', 'eat', 'jeść', 'manger', 'comer'),
  word('drink', 'actions', '🥤', 'drink', 'pić', 'boire', 'beber'),
  word('sleep', 'actions', '😴', 'sleep', 'spać', 'dormir', 'dormir'),
  word('walk', 'actions', '🚶', 'walk', 'chodzić', 'marcher', 'caminar'),
  word('run', 'actions', '🏃', 'run', 'biegać', 'courir', 'correr'),
  word('sit', 'actions', '💺', 'sit', 'siedzieć', 's’asseoir', 'sentarse'),
  word('stand', 'actions', '🧍', 'stand', 'stać', 'se tenir', 'pararse'),
  word('read', 'actions', '📖', 'read', 'czytać', 'lire', 'leer'),
  word('write', 'actions', '✍️', 'write', 'pisać', 'écrire', 'escribir'),
  word('speak', 'actions', '💬', 'speak', 'mówić', 'parler', 'hablar'),
  word('listen', 'actions', '🎧', 'listen', 'słuchać', 'écouter', 'escuchar'),
  word('see', 'actions', '👀', 'see', 'widzieć', 'voir', 'ver'),
  word('cook-action', 'actions', '🍳', 'cook', 'gotować', 'cuisiner', 'cocinar'),
  word('wash', 'actions', '🫧', 'wash', 'myć', 'laver', 'lavar'),
  word('buy', 'actions', '🛒', 'buy', 'kupować', 'acheter', 'comprar'),
  word('work', 'actions', '💼', 'work', 'pracować', 'travailler', 'trabajar'),
  word('play', 'actions', '🎮', 'play', 'grać', 'jouer', 'jugar'),
  word('open', 'actions', '📬', 'open', 'otwierać', 'ouvrir', 'abrir'),
  word('close', 'actions', '🔐', 'close', 'zamykać', 'fermer', 'cerrar'),
  word('give', 'actions', '🤲', 'give', 'dawać', 'donner', 'dar'),
  word('come', 'actions', '➡️', 'come', 'przychodzić', 'venir', 'venir'),
  word('go', 'actions', '🚶‍♂️', 'go', 'iść', 'aller', 'ir'),
  word('wait', 'actions', '⏳', 'wait', 'czekać', 'attendre', 'esperar'),
  word('help', 'actions', '🆘', 'help', 'pomagać', 'aider', 'ayudar'),
  word('look', 'actions', '👀', 'look', 'patrzeć', 'regarder', 'mirar'),
  word('take', 'actions', '📥', 'take', 'brać', 'prendre', 'tomar'),
  word('put', 'actions', '📤', 'put', 'kłaść', 'mettre', 'poner'),
  word('find', 'actions', '🔎', 'find', 'znajdować', 'trouver', 'encontrar'),
  word('lose', 'actions', '🕳️', 'lose', 'gubić', 'perdre', 'perder'),
  word('start', 'actions', '▶️', 'start', 'zaczynać', 'commencer', 'empezar'),
  word('stop-action', 'actions', '⏹️', 'stop', 'przestawać', 'arrêter', 'parar'),
  word('think', 'actions', '💭', 'think', 'myśleć', 'penser', 'pensar'),
  word('know', 'actions', '💡', 'know', 'wiedzieć', 'savoir', 'saber'),
  word('want', 'actions', '🙏', 'want', 'chcieć', 'vouloir', 'querer'),
  word('need', 'actions', '📌', 'need', 'potrzebować', 'avoir besoin', 'necesitar'),
  word('like', 'actions', '❤️', 'like', 'lubić', 'aimer', 'gustar'),
  word('ask', 'actions', '❓', 'ask', 'pytać', 'demander', 'preguntar'),
  word('answer-action', 'actions', '💬', 'answer', 'odpowiadać', 'répondre', 'responder'),
  word('call', 'actions', '📞', 'call', 'dzwonić', 'appeler', 'llamar'),
  word('send', 'actions', '📨', 'send', 'wysyłać', 'envoyer', 'enviar'),
  word('learn', 'actions', '📘', 'learn', 'uczyć się', 'apprendre', 'aprender'),
  word('teach', 'actions', '🧑‍🏫', 'teach', 'uczyć', 'enseigner', 'enseñar'),
  word('remember', 'actions', '🧠', 'remember', 'pamiętać', 'se souvenir', 'recordar'),
  word('forget', 'actions', '🌫️', 'forget', 'zapominać', 'oublier', 'olvidar'),
  word('laugh', 'actions', '😂', 'laugh', 'śmiać się', 'rire', 'reír'),

  word('big', 'descriptions', '🔼', 'big', 'duży', 'grand', 'grande'),
  word('small', 'descriptions', '🔽', 'small', 'mały', 'petit', 'pequeño'),
  word('hot', 'descriptions', '🥵', 'hot', 'gorący', 'chaud', 'caliente'),
  word('cold', 'descriptions', '🥶', 'cold', 'zimny', 'froid', 'frío'),
  word('happy', 'descriptions', '😊', 'happy', 'szczęśliwy', 'heureux', 'feliz'),
  word('sad', 'descriptions', '😢', 'sad', 'smutny', 'triste', 'triste'),
  word('angry', 'descriptions', '😠', 'angry', 'wściekły', 'fâché', 'enfadado'),
  word('tired', 'descriptions', '😫', 'tired', 'zmęczony', 'fatigué', 'cansado'),
  word('hungry', 'descriptions', '😋', 'hungry', 'głodny', 'affamé', 'hambriento'),
  word('thirsty', 'descriptions', '🥤', 'thirsty', 'spragniony', 'assoiffé', 'sediento'),
  word('beautiful', 'descriptions', '✨', 'beautiful', 'piękny', 'beau', 'hermoso'),
  word('new', 'descriptions', '🆕', 'new', 'nowy', 'nouveau', 'nuevo'),
  word('old', 'descriptions', '🧓', 'old', 'stary', 'vieux', 'viejo'),
  word('good', 'descriptions', '👍', 'good', 'dobry', 'bon', 'bueno'),
  word('bad', 'descriptions', '👎', 'bad', 'zły', 'mauvais', 'malo'),
  word('fast', 'descriptions', '⚡', 'fast', 'szybki', 'rapide', 'rápido'),
  word('slow', 'descriptions', '🐌', 'slow', 'wolny', 'lent', 'lento'),
  word('easy', 'descriptions', '🟢', 'easy', 'łatwy', 'facile', 'fácil'),
  word('difficult', 'descriptions', '🧩', 'difficult', 'trudny', 'difficile', 'difícil'),
  word('love', 'descriptions', '💕', 'love', 'miłość', 'amour', 'amor'),
  word('long', 'descriptions', '📏', 'long', 'długi', 'long', 'largo'),
  word('short', 'descriptions', '📌', 'short', 'krótki', 'court', 'corto'),
  word('tall', 'descriptions', '🦒', 'tall', 'wysoki', 'haut', 'alto'),
  word('young', 'descriptions', '🐥', 'young', 'młody', 'jeune', 'joven'),
  word('expensive', 'descriptions', '💎', 'expensive', 'drogi', 'cher', 'caro'),
  word('cheap', 'descriptions', '🪙', 'cheap', 'tani', 'pas cher', 'barato'),
  word('clean', 'descriptions', '✨', 'clean', 'czysty', 'propre', 'limpio'),
  word('dirty', 'descriptions', '🦨', 'dirty', 'brudny', 'sale', 'sucio'),
  word('full', 'descriptions', '🌕', 'full', 'pełny', 'plein', 'lleno'),
  word('empty', 'descriptions', '🕳️', 'empty', 'pusty', 'vide', 'vacío'),
  word('strong', 'descriptions', '💪', 'strong', 'silny', 'fort', 'fuerte'),
  word('weak', 'descriptions', '🫠', 'weak', 'słaby', 'faible', 'débil'),
  word('loud', 'descriptions', '📢', 'loud', 'głośny', 'bruyant', 'ruidoso'),
  word('quiet', 'descriptions', '🤫', 'quiet', 'cichy', 'silencieux', 'silencioso'),
  word('dark', 'descriptions', '🌑', 'dark', 'ciemny', 'sombre', 'oscuro'),
  word('bright', 'descriptions', '🌟', 'bright', 'jasny', 'clair', 'claro'),
  word('left', 'descriptions', '⬅️', 'left', 'lewy', 'gauche', 'izquierdo'),
  word('right', 'descriptions', '➡️', 'right', 'prawy', 'droit', 'derecho'),
  word('busy', 'descriptions', '📅', 'busy', 'zajęty', 'occupé', 'ocupado'),
  word('free', 'descriptions', '🆓', 'free', 'wolny', 'libre', 'libre'),
  word('kind', 'descriptions', '🤗', 'kind', 'miły', 'gentil', 'amable'),
  word('funny', 'descriptions', '🤡', 'funny', 'śmieszny', 'drôle', 'gracioso'),
  word('scared', 'descriptions', '😨', 'scared', 'przestraszony', 'effrayé', 'asustado'),
  word('surprised', 'descriptions', '😲', 'surprised', 'zaskoczony', 'surpris', 'sorprendido'),
  word('warm', 'descriptions', '🌤️', 'warm', 'ciepły', 'tiède', 'templado'),
]

export function getLanguage(code: LangCode): LanguageOption {
  const language = languages.find((item) => item.code === code)
  if (!language) throw new Error(`Unknown language ${code}`)
  return language
}

export function getCategory(id: CategoryId): Category {
  const category = categories.find((item) => item.id === id)
  if (!category) throw new Error(`Unknown category ${id}`)
  return category
}

export function wordsInCategory(
  id: CategoryId,
  knownIds: Iterable<string> = [],
  knownOnly = false,
): Word[] {
  const known = new Set(knownIds)
  return words.filter((item) => {
    if (item.category !== id) return false
    return knownOnly ? known.has(item.id) : !known.has(item.id)
  })
}

export function isLangCode(value: string): value is LangCode {
  return languages.some((language) => language.code === value)
}

export function isCategoryId(value: string): value is CategoryId {
  return categories.some((category) => category.id === value)
}

export function isModeId(value: string): value is ModeId {
  return modes.some((mode) => mode.id === value)
}
